baseURL = "https://www.dhpitt.com"
title = "DH Pitt"
author = "dhpitt"
Owner = "DH Pitt Consulting, LLC"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = false

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['work']

  googleFonts = true

  faviconTouch = "favicon-16x16"
  favicon32 = "favicon-32x32"

  [params.logo]
    #main = "blue-delta-192x192.png"
    main = "/img/logo/dhpitt-banner.png" 
    alt = "My Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "David Pitt"
    owner = "DH Pitt Consulting, LLC"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = false

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

 # [[menu.main]]
 #   identifier = "resume"
 #   name = "Resume"
 #   url = "/resume/"
 #   weight = 2

    [[menu.main]]
    identifier = "work" 
    name = "Work"
    url = "/Work/"
    weight = 2 

#  [[menu.main]]
#    identifier = "contact"
#    name = "Contact"
#    url = "/contact/"
#    weight = 3
#
  [[menu.main]]
    identifier = "cat"
    name = "Cat"
    url = "/cat/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/dhpitt"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
